#!/bin/bash
clear

while [ "$opcionIngreso"!=2 ]
do
clear
	echo " ________________________________________ "
	echo "|                                        |"
	echo "|              ALTA MANUAL               |"
	echo "|________________________________________|"	
	echo "|                                        |"
	echo "|    1- Comenzar a ingresar usuario      |" 
	echo "|    2- Volver                           |"
	echo "|________________________________________|"
	echo
	read -p " Ingrese una opcion:" opcionIngreso


case $opcionIngreso in 

1) clear

#Login
	read -p "Ingrese un login o presione ENTER para volver al menu anterior: " login

if [ "$login" == "" ]
then
echo
        break
fi

busquedaLogin=$(cut -d ":" -f1 /etc/passwd | grep -wi "$login")

if [ "$busquedaLogin" != "" ]
then
echo
        echo "El login ingresado ya existe y estos son sus datos:"
	echo
	finger = "$login"
	echo 	
	read -p "Presione ENTER para volver a intentarlo" volver 
	'break'
	
fi
 	
echo

#Home

	read -p "Ingrese un home: /home/" home

while [ "$home" == "" ]
do
echo
	echo "No se puede continuar sin haber ingresado un home"
	read -p "Vuelva a ingresarle un home al ususario: /home/" home
done

	 busquedaHome=$(cut -d ":" -f6 /etc/passwd | grep -wi "/home/$home")

if  [ "$busquedaHome" == "/home/$home" ] 
then
echo
	echo "El home ingresado ya tiene un usuario propietario."
	read -p "¿Desea continuar y asignarle otros usuarios al mismo home? S/N " confirma

if [ "$confirma" == "S" ] || [ "$confirma" == "s" ] 
then

echo

#Comentario

	read -p "Ingrese un comentario para el usuario (opcional): " comentario
echo

#GrupoPrimario
	read -p "Ingrese un grupo para el usuario: " grupo

if [ "$grupo" == "" ]
then
	echo
	echo "No a ingresado ningun grupo y este se a asignado por defecto"
	
fi

busquedaGrupo=$(cut -d ":" -f3 /etc/group | grep -w "$grupo")

until [ "$busquedaGrupo" == "$grupo" ]

do
echo
	echo "Debe ingresar un grupo existente." 
	read -p "Vuelva a ingresar un grupo para el usuario: " grupo

	busquedaGrupo=$(cut -d ":" -f3 /etc/group | grep -w "$grupo")
done 

echo

#GrupoSecundario
	read -p "Ingrese un grupo secundario (opcional): " grupo2

	busquedaGrupoSecundario=$(cut -d ":" -f3 /etc/group | grep -w "$grupo2")


until [ "$grupo2" == "$busquedaGrupoSecundario" ]
do
echo
        echo "El grupo ingresado no existe."
        read -p "Vuelva a ingresar un grupo: " grupo2

        busquedaGrupoSecundario=$(cut -d ":" -f3 /etc/group | grep -w "$grupo2")
done
	

echo

#Shell
	read -p "Desea ingresar una shell manualmente? S/N: " confirmashell

if [ "$confirmashell" == "n" ] || [ "$confirmashell" == "N" ]
then
echo

echo "Se ha ingresado por defecto la  shell"

elif [ "$confirmashell" == "s" ] || [ "$confirmashell" == "S" ]
then
echo
read -p "Escriba el nombre de la shell que desea utilizar. 
Si no conoce ningun tipo de shell presione enter y elija una: " shell

if [ "$shell" == "" ]
then
echo " ________________ "
echo "|                |"
echo "| TIPOS DE SHELL |"
echo "|________________|"
echo "|                |"
echo "|      bash      |"
echo "|      sh        |"
echo "|      ksh       |"
echo "|      tcsh      |"
echo "|      csh       |"
echo "|________________|"
echo ""
read -p "Escriba el nombre de la shell que desea utilizar: " shell

fi
fi

echo

if [ "$grupo" == "" ] 
then
	useradd "$login" -d /home/"$home" -mk /etc/skel -c "$comentario" -G "$grupo2" -s /bin/"$shell"

elif [ "$shell" == "" ]
then
	useradd "$login" -d /home/"$home" -mk /etc/skel -c "$comentario" -g "$grupo" -G "$grupo2"

elif [ "$confirma" == "S" ] || [ "$confirma" == "s" ]
then 
	useradd "$login" -d /home/"$home" -c "$comentario" -g "$grupo" -G "$grupo2" -s /bin/"$shell" 

elif [ "$grupo" == "" ] && [ "$shell" == "" ]
then
	useradd "$login" -d /home/"$home" -mk /etc/skel -c "$comentario" -G "$grupo2" 

elif [ "$grupo" == "" ] && [ "$confirma" == "S"] [ "$confirma" == "s" ]
then
	useradd "$login" -d /home/"$home" -c "$comentario" -G "$grupo2" -s /bin/"$shell"

elif [ "$shell" == ""] && [ "$confirma" == "S" ] || [ "$confirma" == "s" ]
then
	useradd "$login" -d /home/"$home" -c "$comentario" -g "$grupo" -G "$grupo2"

elif [ "$grupo" == "" ] && [ "$shell" == "" ] && [ "$confirma" == "S" ] || [ "$confirma" == "s" ]
then
	useradd "$login" -d /home/"$home" -c "$comentario" -G "$grupo2"

else
	useradd "$login" -d /home/"$home" -mk /etc/skel -c "$comentario" -g "$grupo" -G "$grupo2" -s /bin/"$shell"
fi

echo

	passwd "$login"
echo

	if [ $? == 0 ]
then
echo
	read -p "Se ha creado el usuario con exito. Presione ENTER para salir" volver
else 

	read -p "Se a producido un error  y no se ha podido ingresar el usuario. Presione ENTER y vuelva a intentarlo" volver

fi

	read -p "Presione ENTER para volver al menu" volver


elif [ "$confrima" == "N" ] || [ "$confirma" == "n" ] 
then
	read -p "A cancelado el ingreso de usuario. Presione ENTER para volver al menu anterior." volver2456787

	break

fi #cierra ultimo elif (confirma)

else 
echo

# EMPIEZA EL ELSE

	#Comentario

        read -p "Ingrese un comentario para el usuario (opcional): " comentario
echo

#GrupoPrimario
        read -p "Ingrese un grupo para el usuario: " grupo

if [ "$grupo" == "" ]
then
        echo
        echo "No a ingresado ningun grupo y este se a asignado por defecto"

fi

	busquedaGrupo=$(cut -d ":" -f3 /etc/group | grep -w "$grupo")

until [ "$busquedaGrupo" == "$grupo" ]

do
echo
        echo "Debe ingresar un grupo existente."
        read -p "Vuelva a ingresar un grupo para el usuario: " grupo

        busquedaGrupo=$(cut -d ":" -f3 /etc/group | grep -w "$grupo")
done

echo

#GrupoSecundario
        read -p "Ingrese un grupo secundario (opcional): " grupo2

        busquedaGrupoSecundario=$(cut -d ":" -f3 /etc/group | grep -w "$grupo2")


until [ "$grupo2" == "$busquedaGrupoSecundario" ]
do
echo
        echo "El grupo ingresado no existe."
        read -p "Vuelva a ingresar un grupo: " grupo2

        busquedaGrupoSecundario=$(cut -d ":" -f3 /etc/group | grep -w "$grupo2")
done


echo

#Shell
        read -p "Desea ingresar una shell manualmente? S/N: " confirmashell

if [ "$confirmashell" == "n" ] || [ "$confirmashell" == "N" ]
then
echo

echo "Se ha ingresado por defecto la  shell"

elif [ "$confirmashell" == "s" ] || [ "$confirmashell" == "S" ]
then
echo 
read -p "Escriba el nombre de la shell que desea utilizar.
Si no conoce ningun tipo de shell presione enter y elija una: " shell

if [ "$shell" == "" ]
then
echo
echo " ________________ "
echo "|                |"
echo "| TIPOS DE SHELL |"
echo "|________________|"
echo "|                |"
echo "|      bash      |"
echo "|      sh        |"
echo "|      ksh       |"
echo "|      tcsh      |"
echo "|      csh       |"
echo "|________________|"
echo
read -p "Escriba el nombre de la shell que desea utilizar: " shell

fi
fi
echo

if [ "$grupo" == "" ]
then
        useradd "$login" -d /home/"$home" -mk /etc/skel -c "$comentario" -G "$grupo2" -s /bin/"$shell"

elif [ "$shell" == "" ]
then
        useradd "$login" -d /home/"$home" -mk /etc/skel -c "$comentario" -g "$grupo" -G "$grupo2"

elif [ "$shell" == "" ] && [ "$grupo" == "" ]
then
        useradd "$login" -d /home/"$home" -mk /etc/skel -c "$comentario" -G "$grupo2"

else
        useradd "$login" -d /home/"$home" -mk /etc/skel -c "$comentario" -g "$grupo" -G "$grupo2" -s /bin/"$shell"
fi

echo

passwd "$login"
echo

	if [ $? == 0 ]
then
echo
	read -p "Se ha creado el usuario con exito. Presione ENTER para salir" volver
else 

	read -p "Se a producido un error  y no se ha podido ingresar el usuario. Presione ENTER y vuelva a intentarlo" volver

fi


	
fi #cierra primer if (home ya existe)
;;

2) break
;;

*)	echo
	echo "La opcion ingresada no es valida."
	read -p "Presione ENTER y vuelva a ingresar una opcion valida" VolverAIngresar3
;;

esac
done


